/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Anyona Zaddock
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    double numberEnter1;
    double numberEnter2;
    double result;
    String operator;
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea = new javax.swing.JTextField();
        btnCE = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        btnOR = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnPLUS = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMINUS = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMUL = new javax.swing.JButton();
        btnZERO = new javax.swing.JButton();
        btnDOT = new javax.swing.JButton();
        btnEQ = new javax.swing.JButton();
        btnDIV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        textArea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(textArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 80));

        btnCE.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        getContentPane().add(btnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 70, 60));

        btnDEL.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        btnDEL.setText("DEL");
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });
        getContentPane().add(btnDEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, 60));

        btnOR.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnOR.setText("+/-");
        btnOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnORActionPerformed(evt);
            }
        });
        getContentPane().add(btnOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 70, 60));

        btnC.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 70, 60));

        btn7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 60));

        btn8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, 60));

        btn9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 70, 60));

        btnPLUS.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnPLUS.setText("+");
        btnPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLUSActionPerformed(evt);
            }
        });
        getContentPane().add(btnPLUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, 60));

        btn4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 70, 60));

        btn5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 70, 60));

        btn6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 70, 60));

        btnMINUS.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnMINUS.setText("-");
        btnMINUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMINUSActionPerformed(evt);
            }
        });
        getContentPane().add(btnMINUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 70, 60));

        btn13.setText("jButton1");
        getContentPane().add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, 60));

        btn14.setText("jButton1");
        getContentPane().add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 70, 60));

        btn15.setText("jButton1");
        getContentPane().add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 70, 60));

        btn16.setText("jButton1");
        getContentPane().add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 70, 60));

        btn1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, 60));

        btn2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 70, 60));

        btn3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 70, 60));

        btnMUL.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnMUL.setText("*");
        btnMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMULActionPerformed(evt);
            }
        });
        getContentPane().add(btnMUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 70, 60));

        btnZERO.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnZERO.setText("0");
        btnZERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZEROActionPerformed(evt);
            }
        });
        getContentPane().add(btnZERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 70, 60));

        btnDOT.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnDOT.setText(".");
        btnDOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOTActionPerformed(evt);
            }
        });
        getContentPane().add(btnDOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 70, 60));

        btnEQ.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnEQ.setText("=");
        btnEQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEQActionPerformed(evt);
            }
        });
        getContentPane().add(btnEQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 70, 60));

        btnDIV.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        btnDIV.setText("/");
        btnDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDIVActionPerformed(evt);
            }
        });
        getContentPane().add(btnDIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 70, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void EnterNumber(String q){
        String num = textArea.getText() + q;
        textArea.setText(num);
    }
    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        String bspace = null;
        
        if(textArea.getText().length() > 0){
            StringBuilder sb = new StringBuilder(textArea.getText());
            sb.deleteCharAt(textArea.getText().length() - 1);
            bspace = sb.toString();
            textArea.setText(bspace);
        }
    }//GEN-LAST:event_btnDELActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        textArea.setText("");
        
        String Fn, Sn;
        
        Fn = String.valueOf(numberEnter1);
        Sn = String.valueOf(numberEnter2);
        
        Fn = "";
        Sn = "";
    }//GEN-LAST:event_btnCActionPerformed

    private void btnORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnORActionPerformed
        double nums = Double.parseDouble(String.valueOf(textArea.getText()));
        nums = (-1) * nums;
        textArea.setText(String.valueOf(nums));
    }//GEN-LAST:event_btnORActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        EnterNumber("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        EnterNumber("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        EnterNumber("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        EnterNumber("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        EnterNumber("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        EnterNumber("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        EnterNumber("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        EnterNumber("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        EnterNumber("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnZEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZEROActionPerformed
        EnterNumber("0");
    }//GEN-LAST:event_btnZEROActionPerformed

    private void btnDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDIVActionPerformed
        numberEnter1 = Double.parseDouble(textArea.getText());
        textArea.setText("");
        operator = "/";
    }//GEN-LAST:event_btnDIVActionPerformed

    private void btnMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMULActionPerformed
        numberEnter1 = Double.parseDouble(textArea.getText());
        textArea.setText("");
        operator = "*";
    }//GEN-LAST:event_btnMULActionPerformed

    private void btnMINUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMINUSActionPerformed
        numberEnter1 = Double.parseDouble(textArea.getText());
        textArea.setText("");
        operator = "-"; 
    }//GEN-LAST:event_btnMINUSActionPerformed

    private void btnPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLUSActionPerformed
        numberEnter1 = Double.parseDouble(textArea.getText());
        textArea.setText("");
        operator = "+";
    }//GEN-LAST:event_btnPLUSActionPerformed

    private void btnDOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOTActionPerformed
        if (! textArea.getText().contains(".")) {
            textArea.setText(textArea.getText() + btnDOT.getText());
        }
    }//GEN-LAST:event_btnDOTActionPerformed

    private void btnEQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEQActionPerformed
        numberEnter2 = Double.parseDouble(textArea.getText());
        
        if (operator == "+") {
            result = numberEnter1 + numberEnter2;
            textArea.setText(String.valueOf(result));
        }
        
        else if (operator == "-") {
            result = numberEnter1 - numberEnter2;
            textArea.setText(String.valueOf(result));
        } 
        
        else if (operator == "*") {
           result = numberEnter1 * numberEnter2;
           textArea.setText(String.valueOf(result)); 
        }
        
        else if (operator == "/") {
            result = numberEnter1 / numberEnter2;
            textArea.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_btnEQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnDIV;
    private javax.swing.JButton btnDOT;
    private javax.swing.JButton btnEQ;
    private javax.swing.JButton btnMINUS;
    private javax.swing.JButton btnMUL;
    private javax.swing.JButton btnOR;
    private javax.swing.JButton btnPLUS;
    private javax.swing.JButton btnZERO;
    private javax.swing.JTextField textArea;
    // End of variables declaration//GEN-END:variables
}
